### ISSUE TITLE
break後の処理について

### ISSUE THREAD

**Issue by c0b2315233** [Drkoukichi/ProjEXD_2#1]
https://github.com/Drkoukichi/ProjEXD_2/blob/b751b3fde88ccfd5b5f086c87a89eab23288192e/dodge_bomb.py#L222

while True:からbreakした後に処理を置くのは、分かりづらいのではないか。
breakする前にこの処理を配置したほうがいいのではないだろうか。

**Comment by Drkoukichi** [comment]
うーん正論
